soundcomm/urls.py
from django.urls import path
from . import views

app_name = 'soundcomm'

urlpatterns = [
    path('select_test', views.select_test, name='select_test'),
    path('config_test', views.config_test, name='config_test'),
    path('loading_page', views.loading_page, name='loading_page')
]

soundresults/urls.py
from django.urls import path
from soundresults import views

app_name = 'soundresults'

urlpatterns = [
        path('view_tests', views.ViewTests.as_view(), name='view_tests'),
        path('view_tests/<test_slug>', views.ViewRuns.as_view(), name='view_runs'),
        path('view_tests/<test_slug>/<config_pk>', views.ViewResults.as_view(), name='view_results'),
        path('view_tests/<test_slug>/<config_pk>/<datum_pk>', views.ViewSegments.as_view(), name='view_segments'),
        path('generate_csv', views.generate_csv, name='generate_csv'),
]

soundstat/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('soundtests/', include('soundtests.urls')),
    path('soundcomm/', include('soundcomm.urls')),
    path('soundresults/', include('soundresults.urls')),
]

soundtests/urls.py
from django.urls import path
from soundtests import views

app_name = 'soundtests'

urlpatterns = [
    # Sound Analysis UI's Homepage 
    path('', views.index, name='index'),
    
    # Views where user uploads
    path('upload_sounds', views.upload_sound, name='upload_sound'),
    path('upload_lesson', views.upload_lesson, name='upload_lesson'),
    path('upload_lesson/sounds', views.upload_lesson_sounds, name='upload_lesson_sounds'),

    # Views that work w/ creating tests
    path('create_test', views.create_test, name='create_test'),
    path('associate_sounds', views.associate_sounds, name='associate_sounds'),

    # Views that display contents
    path('view_tests', views.ViewTests.as_view(), name='view_tests'),
    path('view_tests/<test_slug>', views.ViewTestContents.as_view(), name='view_test_contents'),

    # AJAX views
    path('sound_filter', views.sound_filter, name='sound_filter'),
    path('get_url', views.get_url, name='get_url'),
]

soundtests/models/lesson.py
from django.db import models

class Lesson(models.Model):
    """An object representing a TLO lesson

    Attributes:
        json (dict): A dictionary that mimics TLO's lesson JSON
    
    """

    lesson_name = models.CharField(max_length=150)
    json_name = models.CharField(max_length=150, default="", null=True)
    activity_type = models.CharField(max_length=20)
    learning_language = models.CharField(max_length=50)
    known_language = models.CharField(max_length=50)

    def __str__(self):
        return self.lesson_name

    @property
    def json(self):
        """Returns a dictionary that mimics TLO's Lesson JSON"""

        json_dict = {
                "listName": self.json_name,
                "languageLearn": self.learning_language,
                "languageNative": self.known_language,
                "files": [],
                "os": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
                "userName": "",
                "activityType": "pron"
        }
        for sound in self.associated_sounds.all():
            json_dict["files"].append(sound.json)
        
        return json_dict

    class Meta:
        db_table = 'lessons'

soundtests/forms/_filterform.py
from django import forms
from soundtests.models.sound import Sound
"""
Defines the base filter form from which all others inherit
"""

def distinct_values(field):
    """Helper function which returns distinct values of the appropriate Sound field"""
    return [[x[field], x[field]] for x in Sound.objects.order_by(field).values(field).distinct()]

# SoundChoiceField and SoundPhraseField are defined to alter how they validate.
# Since the choices in these fields will be altered dynamically, they wouldn't
# validate otherwise, so we check to ensure their values are in the database, 
# regardless of what the initial choices were
class SingleSoundField(forms.ChoiceField):
    """Validates javascript changes in ChoiceField"""

    def __init__(self, field, *args, **kwargs):
        """Def. __init__ to require input of field"""
        super(SingleSoundField, self).__init__(*args, **kwargs)
        self.field = field

    def valid_value(self, value):
        filter_dict = {"{}__exact".format(self.field): value}
        if not Sound.objects.filter(**filter_dict):
            return False
        else:
            return True

class MultiSoundField(forms.MultipleChoiceField):
    """Validates javascript changes in MultipleChoiceField"""

    def __init__(self, field, *args, **kwargs):
        """Def. __init__ to require input of field"""
        super(MultiSoundField, self).__init__(*args, **kwargs)
        self.field = field

    def valid_value(self, value):
        filter_dict = {"{}__exact".format(self.field): value}
        if not Sound.objects.filter(**filter_dict):
            return False
        else:
            return True


class SoundFilterForm(forms.Form):
    """
    Filters Sounds according to user selection

    This form is the search-filter for searching words in the database via
    a few clickable parameters. The associated javascript functions 
    called in onChange are located at /static/jscript_functions.js
    """

    # Allows user to filter by sex
    sex = forms.MultipleChoiceField(
            choices=Sound.SEX_CHOICES,
            widget=forms.SelectMultiple(
                attrs={"onChange":"filter_sounds(this)"}
            ),
            required=False
    )

    # Allows user to filter by language
    language = forms.MultipleChoiceField(
            widget=forms.SelectMultiple(
                attrs={"onChange":"filter_sounds(this)"}
            ),
            required=False
    )

    # Allows user to filter by whether or not voice is synthetic
    voice = forms.MultipleChoiceField(
            widget=forms.SelectMultiple(
                attrs={"onChange":"filter_sounds(this)"}
            ),
            required=False
    )

    # Allows user to filter by number of words
    num_words = forms.MultipleChoiceField(
            widget=forms.SelectMultiple(
                attrs={"onChange":"filter_sounds(this)"}
            ),
            required=False
    )

    # Allows user to filter by number of syllables 
    num_syllables = forms.MultipleChoiceField(
            widget=forms.SelectMultiple(
                attrs={"onChange":"filter_sounds(this)"}
            ),
            required=False
    )

    # Allows user to filter by speaker name
    speaker_name = forms.MultipleChoiceField(
            widget=forms.SelectMultiple(
                attrs={"onChange":"filter_sounds(this)"}
            ),
            required=False
    )

    # Displays the unique phrases which adhere to above filters (i.e. - If
    # there are 30 recordings of the word "dog," then we will see only one
    # entry for "dog")
    unique_phrase = MultiSoundField(
            field="phrase1",
            widget=forms.SelectMultiple(
                attrs={
                    "style":"width: 100%", 
                    "onChange":"filter_sounds(this, unique=true)",
                    'size':10
                }
            ),
            required=False
    )
   
    # Displays the recordings available to send to the server; 
    # double-clicking on the choices in this form will play the sound
    sounds_to_send = MultiSoundField(
            field="pk",
            widget=forms.SelectMultiple(
                attrs={
                    "style":"width: 100%",
                    'size':10
                }
            )
    )

    # We must override the __init__ method so that the Language choices update
    # whenever we add sounds w/ a new language
    def __init__(self, *args, **kwargs):
        """
        __init__ method which forces update on change

        The available choices in this form aren't static; they update
        according to whatever is in the database.

        """

        super(SoundFilterForm, self).__init__(*args, **kwargs)
        for field in ['language', 'speaker_name', 'num_words', 'num_syllables']:
            self.fields[field].choices = distinct_values(field)
        self.fields['voice'].choices = [[False, "Natural"], [True, "Synthetic"]]

soundtests/forms/associate_sound_form.py
from ._filterform import SoundFilterForm

from django import forms

class AssociateSoundForm(SoundFilterForm):
    """Adds extra fields to SoundFilterForm to pass data

    Since this inherits from :class:`soundtests.forms.SoundFilterForm`, it
    will also require the 'sounds_to_send' parameter; a list of primary
    keys which, in this case, are the sounds to be sent to the sever.
    
    """

    sound_language = forms.CharField(widget=forms.HiddenInput())
    sound_pk = forms.CharField(widget=forms.HiddenInput())
    master_phrase1 = forms.CharField(widget=forms.HiddenInput())
    master_phrase2 = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        super(AssociateSoundForm, self).__init__(*args, **kwargs)
        self.fields['unique_phrase'].widget.attrs.update({'onChange': 'filter_sounds(this, lessons=false, recording=true)'})

soundresults/views/view_tests.py
from django.views.generic import ListView
from soundtests.models import SoundTest

class ViewTests(ListView):
    """Lists all available tests

    When a user clicks the "View Test Contents" link on the homepage, this view
    is called.
    """
    context_object_name = 'soundtests'
    model = SoundTest
    paginate_by = 10
    template_name = 'soundresults/view_tests.html'

soundtests/views/associate_sounds.py
from django.forms import formset_factory
from django.shortcuts import render, redirect

from soundtests.forms import AssociateSoundForm, AssociateSoundFormset
from soundtests.models import Sound

def associate_sounds(request):
    """Called after a user chooses name, description, and lesson when creating a test
    
    This either calls the save() method on the form (in the case that
    master-to-master is checked, or redirects the user to the page where each
    master sound in the test can be directed to a set of user sounds

    """
    AssociateSoundFormset_factory = formset_factory(
            form=AssociateSoundForm,
            formset=AssociateSoundFormset,
            extra=0,
    )
    test_data = {
            'name': request.session['test_name'], 
            'description': request.session['test_description']
    }

    # User was redirected
    if request.method == 'GET':
        sound_info = []                                                 
        for sound_key in request.session['test_keys']:    
            sound = Sound.objects.get(pk=sound_key)                     
            tmp_info = {                                                
                'sound_language': sound.language,                       
                'sound_pk': sound.pk,                                   
                'master_phrase1': sound.phrase1,                        
                'master_phrase2': sound.phrase2,                        
            }                                                           
            sound_info.append(tmp_info)                                 
        formset = AssociateSoundFormset_factory(
                initial=sound_info,
                test_data=test_data
        ) 
    
    # User submitted this form
    if request.method == 'POST':
        formset = AssociateSoundFormset_factory(
                data=request.POST, 
                test_data=test_data
        )

        if formset.is_valid():
            formset.save()
            return redirect('soundtests:index')

    return render(request, 'soundtests/associate_sounds.html', {'formset': formset})

soundtests/views/create_test.py
from django.shortcuts import render, redirect
from soundtests.forms import SoundTestForm

def create_test(request):
    """Displays form to create a test"""
   
    if request.method == 'POST':
        form = SoundTestForm(request.POST, prefix='form-0')
        if form.is_valid():
            if request.POST.get('form-0-master_to_master_test'):
                form.save()
                return redirect('soundtests:index')

            else:
                # If this is not a master-to-master test, send user to associate
                # sounds page
                request.session['test_name'] = form.cleaned_data['name']
                request.session['test_description'] = form.cleaned_data['description']
                request.session['test_keys'] = [pk for pk in request.POST.getlist('master_sounds[]')]

                return redirect('soundtests:associate_sounds')
    else:
        form = SoundTestForm(prefix='form-0') # The javascript necessitates this prefix
    return render(request, 'soundtests/create_test.html', {'form': form})

soundtests/views/get_url.py
from django.http import JsonResponse
from soundtests.models import Sound

def get_url(request):
    """Sends back sound's URL on AJAX request. Used w/ javascript function 'play_sound()' """
    if request.is_ajax() and request.method == 'GET':
        sound = Sound.objects.get(pk=request.GET.get('pk'))
        return JsonResponse({'url': sound.url})

soundtests/views/index.py
from django.shortcuts import render

def index(request):
    return render(request, "soundtests/index.html")

soundtests/views/sound_filter.py
from django.http import HttpResponse
from soundtests.models.sound import Sound

import json

def sound_filter(request):
    """Deals with AJAX requests sent by the SoundFilterForm

    To add another filter, simply add another if clause w/ the appropiate list
    sent when the user clicks on a particular attribute in the form:

    if 'new_parameter[]' in search_values:
        sounds = sounds.filter(new_parameter__in = request.GET.getlist('new_parameter[]'))

    Don't forget to add to the 'data' sent in the Ajax request defined in
    :ref:`static.javascript.filter_sounds.js`
    
    All of the sounds filtered are ultimately passed to unique_phrase_json, 
    which is what is returned to the javascript function (and displayed on
    the resulting form to the user)

    """

    # Checks for AJAX call - When user clicks one of the 3 filters, return
    # the list of unique phrases that match these filters
    if request.is_ajax():
        sounds = Sound.objects.all()
        search_values = list(request.GET.keys())
        lesson_filter = request.GET.get("lessons")
        recording_filter = request.GET.get('recording')
        if 'sex[]' in search_values:
            sounds = sounds.filter(sex__in = request.GET.getlist('sex[]'))

        if 'language[]' in search_values:
            sounds = sounds.filter(language__in = request.GET.getlist('language[]'))

        if 'speaker[]' in search_values:
            sounds = sounds.filter(speaker_name__in = request.GET.getlist('speaker[]'))

        if 'voice[]' in search_values:
            sounds = sounds.filter(voice__in = request.GET.getlist('voice[]'))

        if 'num_syllables[]' in search_values:
            sounds = sounds.filter(num_syllables__in = request.GET.getlist('num_syllables[]'))

        if 'num_words[]' in search_values:
            sounds = sounds.filter(num_words__in = request.GET.getlist('num_words[]'))

        if lesson_filter == 'true':
            sounds = sounds.filter(associated_lesson__isnull=False)

    # Checks for AJAX call - When user clicks one of the unique phrases, return a list of all
    # sounds which match that phrase
        if recording_filter == 'true':
            recordings = []
            sounds = sounds.filter(phrase1__in=request.GET.getlist('unique_phrase[]'))
            for count, sound in enumerate(sounds):
                recordings.append({
                    'key': sound.pk,
                    'display': "Recording #" + str(count + 1) + " - ",
                    'phrase1': sound.phrase1,
                    'phrase2': sound.phrase2,
                    'language': sound.language
                })
            return HttpResponse(json.dumps(recordings))

        else:
            phrases = []
            unique_phrase_json = [] 
            for sound in sounds:
                if sound.phrase1 not in phrases:
                    phrases.append(sound.phrase1)
                    unique_phrase_json.append({'phrase1': sound.phrase1, 'phrase2': sound.phrase2})

            unique_phrase_json = sorted(unique_phrase_json, key=lambda k: k['phrase2'])
            return HttpResponse(json.dumps(unique_phrase_json))

soundtests/views/upload_lesson.py
from django.shortcuts import redirect, render
from soundtests.forms import LessonForm

def upload_lesson(request):
    """Displays form Used when user uploads lesson JSON"""
    if request.method == "POST":
        form = LessonForm(request.POST, request.FILES)
        if form.is_valid():
            request.session["cleaned_data"] = form.cleaned_data
            return redirect("soundtests:upload_lesson_sounds")

    else:
        form = LessonForm()
    return render(request, "soundtests/upload_lesson.html", {"form": form})

soundtests/templates/soundtests/_filterform.html
<!-- 
    This template is imported whenever a page has a sound-filter form
    One must still include the csrf_token, form.errors, and
    form.non_field_errors in whatever template which includes this
-->
{% load static %}
</tr>
    <td><strong>Word Filter:</strong></td>
</tr>
    <td>Sex, Starts w/, Language</td>
    <td>{{ form.sex }} {{ form.language }}</td>
</tr>
<tr>
    <td>Speaker Name, Type-of-Voice<br>Num. Words, Num. Syllables</td>
    <td>{{ form.speaker_name }} {{ form.voice }} {{ form.num_words }} {{ form.num_syllables }}</td>
</tr>
<tr>
    <td><hr/></td>
    <td><hr/></td>
</tr>
<tr>
    <td><strong>Phrase:</strong></td>
    <td>{{ form.unique_phrase }}</td>
<tr>
    <td><strong>Recordings:</strong></td>
    <td>{{ form.sounds_to_send }}</td>
</tr>

<script type="text/javascript" src="{% static 'javascript/play_sound.js' %}"></script>

soundtests/templates/soundtests/create_test.html
{% load static %}
<html>
    <body>
        <h1>Create New Test</h1>
        Please include a descriptive title and a detailed description of what you're testing. For example,
        an appropriate title would be: "Single Consonant Substitution in Short, English words"
        <br>
        <br>
        Choosing a sound from the below form and clicking the "Add Selected Sounds to Test" button will
        do exactly that (add a sound to the test). Clicking the "Associate Sounds" button will finalize
        the master-sounds of your test and redirect to a page where one can associate user sounds to 
        each master sound. Checking the "Master-to-Master" box means that each master sound will be sent
        to itself (there is therefore no need to redirect to the associate-sounds page)
        <form method="POST">
            {% csrf_token %}
            {{ form.errors }}
            {{ form.non_field_errors }}
            <table>
                <tr>
                    <td><strong>Test Name:</strong></td>
                    <td>{{ form.name }}</td>
                </tr>
                <tr>
                    <td><strong>Description:</strong></td>
                    <td>{{ form.description }}</td>
                </tr>
                {% include "soundtests/_filterform.html" with form=form %}
                <tr>
                    <td><strong>Master-to-Master?</strong></td>
                    <td>{{ form.master_to_master_test }}</td>
                </tr>
            </table>
            <button type="button" onclick=add_sound()>Add Selected Sounds to Test</button>
            <br>
            <br>
            <div id="master_sounds">
                {{ form.master_sounds }}
            </div>
            <table id="test_table" border=1>
                <tr>
                    <td><strong>Language</strong></td>
                    <td><strong>Phrase 1</strong></td>
                    <td><strong>Phrase 2</strong></td>
                </tr>
            </table>
            <br>
            <br>
            <button type='submit'>Associate Sounds</button>
        </form>
        <a href="{% url 'soundtests:index' %}">Back to Home</a>

        <!-- Scripts -->
        <script type="text/javascript" src="{% static 'javascript/jquery-3.3.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'javascript/filter_sounds.js' %}"></script>
        <script type="text/javascript" src="{% static 'javascript/add_sound.js' %}"></script>
    </body>
</html>

soundtests/templates/soundtests/index.html
<http>

<h1>Soundstat - Sound Server Testing</h1>
<h2>Upload Materials</h2>
<a href={% url 'soundtests:upload_sound' %}>Upload Sounds</a>
<br>
<a href ={% url 'soundtests:upload_lesson' %}>Upload Lesson JSON</a>
<br>
<h2>Testing</h2>
<a href={% url 'soundtests:create_test' %}>Create New Test</a>
<br>
<a href={% url 'soundtests:view_tests' %}>View Test Contents</a>
<br>
<a href={% url 'soundcomm:select_test' %}>Run Test/s</a>
<br>
<h2>Results</h2>
<a href={% url 'soundresults:view_tests' %}>View Test Results</a>
<h2>Links</h2>
<a href='/flower'>Flower - Task Monitoring & Management</a> (When running tests, the tasks can be monitored via here)
<br>
[REDACTED]
</http>

soundtests/templates/soundtests/uplesson.html
<h1>Upload Lesson</h1>
Upload lesson JSON. To aquire JSON for a particular lesson, open Fiddler and access the list. 
Make sure it is a list. To the left of the title will be an icon that looks like this:
<br> 
<img src=/static/images/list_icon.PNG>
<br>
<br>
In Fiddler, look at the requests whose HOSTs are either "192.168.254.77" or sound.transparent.com
(these are the IPs of the TEST sound server and LIVE sound server respectively; whichever one 
you're on will be the one that shows up). 
<br>
<br>
Generally, the request you're looking for has a BODY
of 23. When clicking on it and setting the view to JSON, you should see JSON that begins with 
"activityType=pron". When you find this request, right click it, click Save, Request, Request Body.
This file is the one you want to upload here.
<br>
<br>
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
<table>
    {{ form }}
</table>
<br>    
<button type="submit">Classify this Lesson's Sounds</button>
<br>
<br>
<a href="{% url 'soundtests:index' %}">Back to Home</a>

soundtests/templates/soundtests/uplesson_sounds.html
<meta charset='utf-8'>
<h1>Classify Lesson's Sounds</h1>
<h3>
    Language: {{ language }}
    <br>
    Lesson Name: {{ lesson }}
    <br>
    Lesson Name (in TLO's JSON): {{ list }}
    <br>
    Number of Words: {{ num_words }}
</h3>
Typically, "Phrase1" is the English translation of the phrase, and "Phrase2" is the phrase written in its original language. (Since the sounds are not yet saved into the database, they must be played from TLO's URL; if the lesson is on education.transparent.com, sometimes this does not work). 
<br>
<br>
<br>
<form method="post">
    {% csrf_token %}
    {{ formset.management_form }}
    {% for form in formset %}
        <table frame='box'>
            <tr><a href="javascript:void(0);" onclick="javascript:sound = new Audio('{{ form.url.value }}'); sound.play()">Play Sound</a></tr>
            {{ form }}
        </table>
        <br>
        <br>
    {% endfor %}
    <button type="submit">Submit Sounds</button>
</form>
<br>
<br>
<a href="{% url 'soundtests:index' %}">Back to Home</a>

soundtests/templates/soundtests/upload_lesson_sounds.html
<html>
    <body>
    <h1>Classify Lesson's Sounds</h1>
    <h3>
        Learning Language: {{ formset.lesson_dict.learning_language }}
        <br>
        Known Language: {{ formset.lesson_dict.known_language }}
        <br>
        Lesson Name: {{ formset.lesson_dict.lesson_name }}
        <br>
        Lesson Name (in TLO's JSON): {{ formset.lesson_dict.json_name }}
        <br>
        Number of Words: {{ formset.forms|length }}
    </h3>
Typically, "Phrase1" is the English translation of the phrase, and "Phrase2" is the phrase written in its original language. (Since the sounds are not yet saved into the database, they must be played from TLO's URL; if the lesson is on education.transparent.com, sometimes this does not work). 
<hr>
<br>
<br>

        <form method="POST">
            {% csrf_token %}
            <table>
                {{ formset.subform.errors }}
                {{ formset.subform }} 
            </table>
            <br>
            <br>
            {{ formset.management_form }}
            {% for form in formset %}
                <table frame="box">
                    {{ form }}
                    <br>
                </table>
            {% endfor %}
            <br>
            <button type=Submit>Submit</button>
        </form>
        <br>
        <a href="{% url 'soundtests:index' %}">Back to Home</a>
    </body>
</html>

soundtests/templates/soundtests/upload_sound.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <title>Upload Sound</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>

    <body>
        <h1>Upload or Record Sound</h1>
        Please upload or record your sound/s. 
        <br>
        <br>
        If multiple sounds have the same information (i.e. - You'd like
        to upload several different recordings of the same word), put these 
        files in the same directory and select all of them after clicking
        the "Browse" button.
        <br>
        <br>
        <br>

        <!-- Beginning of Sound Form -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
            {{ form }} 
            </table>
            <button type="submit">Submit File/s</button>
        </form>

        <!-- Beginning of the Recording Module -->
        <h2>Record Sound</h2>
        <table id='error_table'>
            <tbody>
            </tbody>
        </table>
        <div id="controls">
            <button id="recordButton">Record</button>
            <button id="pauseButton" disabled>Pause</button>
            <button id="stopButton" disabled>Stop</button>
        </div>
        <div id="formats">Format: start recording to see sample rate</div>
        <h3>Recordings</h3>
        <ol id="recordingsList"></ol>

        <!-- Scripts -->
        <script src="{% static 'javascript/recorder.js' %}"></script>
        <script src="{% static 'javascript/recorder_app.js' %}"></script>
        <script type="text/javascript" src="{% static 'javascript/jquery-3.3.1.min.js' %}"></script>
        <br>
        <a href="{% url 'soundtests:index' %}">Back to Home</a>
    </body>
</html>

soundtests/templates/soundtests/upsound.html
<head>
{% load static %}
<!--<meta http-equiv="Content-type" content="text/html; charset=utf-8" />-->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script type="text/javascript" src="{% static 'jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'jscript_functions.js' %}"></script>
</head>
<body>


<h1>Upload or Record Sound</h1>
Please upload or record your sound/s. 
<br>
<br>
If multiple sounds have the same information (i.e. - You'd like
to upload several different recordings of the same word), put these files in the same directory
and select all of them after clicking the "Browse" button. Double click a master sound to play its audio. Single click to fill the form with appropriate information (changing the speaker name and any other such things as needed).
<br>
<br>
<hr>
<h3>Sound Info (Required)</h3>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ form }}
    </table>
    <button type="submit">Submit</button>
</form>

<div id="container">
    <div id="player">
        <h3>Recording</h3>
        <table id="error_table">
            <tbody>
            </tbody>
        </table>
        <div id="controls">
            <button id="recordButton">Record</button>
            <button id="pauseButton" disabled>Pause</button>
            <button id="stopButton" disabled>Stop</button>
        </div>
        <div id="formats">Format: start recording to see sample rate</div>
        <h3>Recordings</h3>
        <ol id="recordingsList"></ol>

    </div>
</div>
<br>
<p id="counter">Submitted Recordings: 0</p>
<br>
<table>
    <tr>
        <td><strong>Word Filter:</strong></td>
    </tr>
        <td>Sex, Starts w/, Language</td>
        <td>{{ available_masters.sex }} {{ available_masters.starts_with }} {{ available_masters.language }}</td>
    </tr>
    <tr>
        <td>Speaker Name, Type-of-Voice<br>Num. Words, Num. Syllables</td>
        <td>{{ available_masters.speaker }} {{ available_masters.voice }} {{ available_masters.num_words }} {{ available_masters.num_syllables }}</td>
    </tr>
    <tr>
        <td><hr/></td>
        <td><hr/></td>
    </tr>
    <tr>
        <td><strong>Phrase:</strong></td>
        <td>{{ available_masters.unique_phrase }}</td>
    <tr>
        <td><strong>Master Sounds:</strong></td>
        <td>{{ available_masters.sounds_to_send }}</td>
    </tr>
</table>

<br>
<script type="text/javascript" src="{% static 'recorder.js' %}"></script>
<script src="https://cdn.rawgit.com/mattdiamond/Recorderjs/08e7abd9/dist/recorder.js"></script>
Credit for recording features goes to Daniel Storey: <a href="https://github.com/danielstorey/WebAudioTrack">https://github.com/danielstorey/WebAudioTrack</a>
</body>
<br>
<a href="{% url 'soundtests:index' %}">Back to Home</a>

soundtests/templates/soundtests/view_tests.html
<html>
    {# Table to show tests #}
    <table border=1>
        <tr>
            <td>Test Name</td><td>Description</td><td>Last Run Date</td>
        </tr>
        {% for test in soundtests %}
        <tr>
            <td><a href={% url 'soundtests:view_test_contents' test_slug=test.slug %}>{{ test.name }}</a></td>
            <td>{{ test.description }}</td>
            <td>{{ test.last_run }}</td>
        </tr>
        {% endfor %}
    </table>

    {# Pagination Section #}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                <a href='?page={{ page_obj.previous_page_number }}'>previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                <a href='?page={{ page_obj.next_page_number }}'>next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
    <br>
    <br>
    <a href={% url 'soundtests:index' %}>Back to Home</a>
</html>

soundtests/templates/soundtests/viewlessons.html
<table border=1>
    <tr>
        <td><strong>Lesson Name</strong></td>
        <td><strong>Lesson Name (in TLO)</strong></td>
        <td><strong>Learning Language</strong></td>
        <td><strong>Known Language</strong></td>
    </tr>
    {% for lesson in lessons %}
    <tr>
        <td><a href="contents/{{ lesson.pk }}/" >{{ lesson.lesson_name }}</a></td>
        <td>{{ lesson.json_name }}</td>
        <td>{{ lesson.learning_language }}</td>
        <td>{{ lesson.known_language }}</td>
    </tr>
    {% endfor %}
</table>
<br>
<a href="{% url 'soundtests:index' %}">Back to Home</a>