soundcomm/urls.py
from django.urls import path
from . import views

app_name = 'soundcomm'

urlpatterns = [
    path('select_test', views.select_test, name='select_test'),
    path('config_test', views.config_test, name='config_test'),
    path('loading_page', views.loading_page, name='loading_page')
]

soundresults/urls.py
from django.urls import path
from soundresults import views

app_name = 'soundresults'

urlpatterns = [
        path('view_tests', views.ViewTests.as_view(), name='view_tests'),
        path('view_tests/<test_slug>', views.ViewRuns.as_view(), name='view_runs'),
        path('view_tests/<test_slug>/<config_pk>', views.ViewResults.as_view(), name='view_results'),
        path('view_tests/<test_slug>/<config_pk>/<datum_pk>', views.ViewSegments.as_view(), name='view_segments'),
        path('generate_csv', views.generate_csv, name='generate_csv'),
]

soundstat/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('soundtests/', include('soundtests.urls')),
    path('soundcomm/', include('soundcomm.urls')),
    path('soundresults/', include('soundresults.urls')),
]

soundtests/urls.py
from django.urls import path
from soundtests import views

app_name = 'soundtests'

urlpatterns = [
    # Sound Analysis UI's Homepage 
    path('', views.index, name='index'),
    
    # Views where user uploads
    path('upload_sounds', views.upload_sound, name='upload_sound'),
    path('upload_lesson', views.upload_lesson, name='upload_lesson'),
    path('upload_lesson/sounds', views.upload_lesson_sounds, name='upload_lesson_sounds'),

    # Views that work w/ creating tests
    path('create_test', views.create_test, name='create_test'),
    path('associate_sounds', views.associate_sounds, name='associate_sounds'),

    # Views that display contents
    path('view_tests', views.ViewTests.as_view(), name='view_tests'),
    path('view_tests/<test_slug>', views.ViewTestContents.as_view(), name='view_test_contents'),

    # AJAX views
    path('sound_filter', views.sound_filter, name='sound_filter'),
    path('get_url', views.get_url, name='get_url'),
]

soundresults/views.py
# -*- coding: utf-8 -*-

import csv
import io
import tempfile
import shutil
import logging
import json

from datetime import datetime
from numpy import mean, median, std

from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import render, redirect

from soundtests.models.testmodels import SoundTest, TestConfig
from soundresults.models.datamodels import PartOfSpeech
from soundresults.forms import TestFilterForm

logger = logging.getLogger('standard_logger')

def tests(request):
    """
    View that displays all available tests
    """
    form = TestFilterForm()
    tests = SoundTest.objects.all()
    return render(request, 'soundresults/viewtests.html', {'tests':tests, 'form':form})


def runs(request, test_key):
    """
    View that displays all the runs for an available test
    """

    test = SoundTest.objects.get(pk=test_key)
    runs = test.runs.all()
            
    return render(request, 'soundresults/viewruns.html', {'name': test.name, 'runs': runs})


def results(request, test_key, run_key):
    """
    View that displays a table of results for a particular test run
    """

    test = SoundTest.objects.get(pk=test_key)
    test_run = test.runs.get(pk=run_key)
   
    score_list = []
    for datum in test_run.data.all():
        score_list.append(datum.score)

    return render(
            request, 
            'soundresults/viewresults.html', 
            {
                'name': test.name, 
                'data': test_run.data.all(),
                'score_mean': round(mean(score_list), 3),
                'score_median': round(median(score_list), 3),
                'score_std': round(std(score_list), 3)
            }
    )

def generate_csv(request):
    """
    This view doesn't actually display anything, but generates a CSV for the "Download CSV" 
    button
    """

    if request.method == 'POST':
        logger.info("Generating CSV...")
        try:
            results = TestConfig.objects.filter(pk__in = request.POST.getlist('runs[]'))
        except ValueError:
            results = TestConfig.objects.filter(jsession_id__in = request.POST.getlist('runs[]'))
        
        segments = PartOfSpeech.objects.filter(associated_datum__result_from__in=results)
        
        # Get the maximum number of words, syllables and phonemes of a phrase (to size CSV header appropriately)
        max_dict = {'WORD':0, 'SYLLABLE':0, 'PHONEME':0}
        for key in max_dict.keys():
            max_dict[key] = max([
                k['num'] for k in segments.filter(type_of_speech=key).values('associated_datum').annotate(num=Count('pk'))
            ])
        
        logger.info(request.POST.getlist('runs[]'))
        csv_buffer = io.StringIO()
        data_writer = csv.writer(csv_buffer)

        # Write title row
        logger.info("Constructing & writing header row...")
        # Construct header row
        row = [
            "score", "snr",
            "mlanguage", "mphrase1", "mphrase2", "mspeaker", "msex", "msynthetic", "mnum_words", 
            "mnum_syllables", "mstarts_with", 
            "ulanguage", "uphrase1", "uphrase2", "uspeaker", "usex", "usynthetic", "unum_words", 
            "unum_syllables", "ustarts_with", "ulen",
            "added_silence", "compare_time", "server", "server_version", "date", "test_name",
            "jsession_id"
        ]
        for key in max_dict.keys():
            for ii in range(1, max_dict[key] + 1):
                row.append('{}_{}_{}'.format(key, ii, 'status')) # i.e. - 'SYLLABLE_3_status'
                row.append('{}_{}_{}'.format(key, ii, 'score')) # i.e. - 'WORD_2_score'
                row.append('{}_{}_{}'.format(key, ii, 'tran')) # i.e. - 'PHONEME_6_tran'
        
        data_writer.writerow(row)
        for result in results: # For every result the user selected
            for datum in result.data.all(): #For every datum in the results data
                row = [
                        datum.score,
                        datum.snr,
                        datum.sounds.master_sound.language,
                        datum.sounds.master_sound.phrase1,
                        datum.sounds.master_sound.phrase2,
                        datum.sounds.master_sound.speaker_name,
                        datum.sounds.master_sound.sex,
                        datum.sounds.master_sound.voice,
                        datum.sounds.master_sound.num_words,
                        datum.sounds.master_sound.num_syllables,
                        datum.sounds.master_sound.starts_with,
                        datum.sounds.user_sound.language,
                        datum.sounds.user_sound.phrase1,
                        datum.sounds.user_sound.phrase2,
                        datum.sounds.user_sound.speaker_name,
                        datum.sounds.user_sound.sex,
                        datum.sounds.user_sound.voice,
                        datum.sounds.user_sound.num_words,
                        datum.sounds.user_sound.num_syllables,
                        datum.sounds.user_sound.starts_with,
                        datum.u_length,
                        result.added_silence,
                        datum.compare_time,
                        result.server,
                        result.server_version,
                        result.date,
                        result.associated_test.name,
                        result.jsession_id
                ]

                for key in max_dict.keys():
                    segments = datum.segments.filter(type_of_speech=key) # All segments of type 'key' (i.e. - WORD)
                    for segment in reversed(segments):
                        row.append(segment.raw_status) # Add status to row
                        row.append(segment.score) # Add score to row
                        row.append(segment.transcription) # Add transcription to row
                    # If there are fewer segments than the max-number, make sure these
                    # cells are empty
                    for ii in range(max_dict[key] - len(segments)):
                        row.append('')
                        row.append('')
                        row.append('')
                data_writer.writerow(row)

        csv_buffer.seek(0)
        if not request.POST.get("runs[]"):
            return HttpResponse("YOU NEED TO SELECT AT LEAST ONE RUN. NOW USE THE BACK BUTTON >:(")

        if request.POST.get("download_csv"):
            logger.info("Serving CSV to client...")
            filename = request.POST.get("test_name") + "-" + datetime.now().strftime("%Y-%m-%d_%H-%M-%S") + ".csv"
            response = HttpResponse(csv_buffer, content_type='application/x-download')
            response['Content-Disposition'] = 'attachment;filename="' + filename + '"'
            return response

        elif request.POST.get("explore_data"):
            logger.info("Creating TMP CSV File for Shiny's use...")
            tmp_csv_file = tempfile.NamedTemporaryFile(mode='w', dir='./tmp_data', delete=False, encoding='utf-8')
            shutil.copyfileobj(csv_buffer, tmp_csv_file)
            tmp_csv_file.seek(0)
            shutil.chown(tmp_csv_file.name, user=999, group=999)
            shiny_url = '/soundshine?tmp_file_name=' + tmp_csv_file.name.replace('/soundstat/tmp_data/','')
            logger.info("Tmp. File name: " + tmp_csv_file.name + " - " + "Redirected URL: " + shiny_url)
            return redirect(shiny_url)

def filter_tests(request):
    """
    This view's sole purpose is to deal with the AJAX requests that are sent by the
    TestFilterForm. To add another filter, simply add another if clause w/ the appropiate
    list sent when the user clicks on a particular attribute in the form
    """

    # Checks for AJAX call - When user clicks one of the 3 filters, return
    # the list of unique phrases that match these filters
    if request.is_ajax():
        configs = TestConfig.objects.all()
        search_values = list(request.GET.keys())
        if 'test_name[]' in search_values:
            tests = SoundTest.objects.filter(name__in = request.GET.getlist('test_name[]'))
            configs = configs.filter(associated_test__in = tests.all())

        if 'server_version[]' in search_values:
            configs = configs.filter(server_version__in = request.GET.getlist('server_version[]'))

        if 'date_start' in search_values:
            try:
                configs = configs.filter(date__gte=datetime.strptime(request.GET.get('date_start'), '%m/%d/%Y'))
            except ValueError:
                pass

        if 'date_end' in search_values:
            try:
                configs = configs.filter(date__lte = datetime.strptime(request.GET.get('date_end'), '%m/%d/%Y'))
            except ValueError:
                pass
        configs = configs.filter(date__isnull=False)
        configs = sorted(configs, key=lambda x: x.date)
        jsession_ids = [{'id':x.jsession_id, 'date':x.date.strftime('%m/%d/%Y - %H:%M'), 'test':x.associated_test.name} for x in configs]
        return HttpResponse(json.dumps(jsession_ids))

soundresults/views/generate_csv.py
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils import timezone
from soundtests.models import TestConfig
from soundresults.models import SegmentDatum

import csv
import io
import shutil
import tempfile

def generate_csv(request):
    """Generates a CSV of selected test runs
    
    This view doesn't display anything, but generates a CSV which is either
    downloaded by the user or sent to the Shiny container (as of now, CSV
    is the easiest way to communicate between Django and Shiny)

    """
    
    if request.method == 'POST':
        if request.POST.get('runs[]'):
            results = TestConfig.objects.filter(pk__in = request.POST.getlist('runs[]'))
            segments = SegmentDatum.objects.filter(associated_datum__result_from__in=results)
            
            # Get the maximum number of words, syllables and phonemes of a phrase (to size CSV header appropriately)
            max_dict = {'WORD':0, 'SYLLABLE':0, 'PHONEME':0}
            for key in max_dict.keys():
                max_dict[key] = max([
                    k['num'] for k in segments.filter(type_of_speech=key).values('associated_datum').annotate(num=Count('pk'))
                ])
            
            csv_buffer = io.StringIO()
            data_writer = csv.writer(csv_buffer)

            # Construct header row
            header_row = [
                'score', 
                'snr',
                'mlanguage', 
                'mphrase1', 
                'mphrase2', 
                'mspeaker', 
                'msex', 
                'msynthetic', 
                'mnum_words', 
                'mnum_syllables', 
                'ulanguage', 
                'uphrase1', 
                'uphrase2', 
                'uspeaker', 
                'usex', 
                'usynthetic', 
                'unum_words', 
                'unum_syllables', 
                'u_len',
                'added_silence', 
                'compare_time', 
                'server', 
                'server_version', 
                'date', 
                'test_name',
                'jsession_id'
            ]

            for key in max_dict.keys():
                for ii in range(1, max_dict[key] + 1):
                    header_row.append('{}_{}_{}'.format(key, ii, 'status')) # i.e. - 'SYLLABLE_3_status'
                    header_row.append('{}_{}_{}'.format(key, ii, 'score')) # i.e. - 'WORD_2_score'
                    header_row.append('{}_{}_{}'.format(key, ii, 'tran')) # i.e. - 'PHONEME_6_tran'
            
            data_writer.writerow(header_row)
            for result in results: # For every result the user selected
                for datum in result.data.all(): # For all data in the results data
                    row = [
                            datum.score,
                            datum.snr,
                            datum.sounds.master_sound.language,
                            datum.sounds.master_sound.phrase1,
                            datum.sounds.master_sound.phrase2,
                            datum.sounds.master_sound.speaker_name,
                            datum.sounds.master_sound.sex,
                            datum.sounds.master_sound.voice,
                            datum.sounds.master_sound.num_words,
                            datum.sounds.master_sound.num_syllables,
                            datum.sounds.user_sound.language,
                            datum.sounds.user_sound.phrase1,
                            datum.sounds.user_sound.phrase2,
                            datum.sounds.user_sound.speaker_name,
                            datum.sounds.user_sound.sex,
                            datum.sounds.user_sound.voice,
                            datum.sounds.user_sound.num_words,
                            datum.sounds.user_sound.num_syllables,
                            datum.u_len,
                            result.added_silence,
                            datum.compare_time,
                            result.server,
                            result.server_version,
                            result.date,
                            result.associated_test.name,
                            result.jsession_id
                    ]

                    for key in max_dict.keys():
                        segments = datum.segments.filter(type_of_speech=key) # All segments of type 'key' (i.e. - WORD)
                        for segment in reversed(segments):
                            row.append(segment.raw_status) # Add status to row
                            row.append(segment.score) # Add score to row
                            row.append(segment.transcription) # Add transcription to row

                        # If there are fewer segments than the max-number, make sure these
                        # cells are empty
                        for ii in range(max_dict[key] - len(segments)):
                            row.append('')
                            row.append('')
                            row.append('')
                    data_writer.writerow(row)

            csv_buffer.seek(0)
        
        if not request.POST.get("runs[]"):
            return HttpResponse("YOU NEED TO SELECT AT LEAST ONE RUN. NOW USE THE BACK BUTTON >:(")

        if request.POST.get("download_csv"):
            filename = '{}-{}.csv'.format(results[0].associated_test.slug, timezone.now().strftime("%Y-%m-%d_%H-%M-%S"))
            response = HttpResponse(csv_buffer, content_type='application/x-download')
            response['Content-Disposition'] = 'attachment;filename={}'.format(filename)
            return response

        elif request.POST.get("explore_data"):
            tmp_csv_file = tempfile.NamedTemporaryFile(mode='w', dir='./tmp_data', delete=False, encoding='utf-8')
            shutil.copyfileobj(csv_buffer, tmp_csv_file)
            tmp_csv_file.seek(0)
            shutil.chown(tmp_csv_file.name, user=999, group=999)
            shiny_url = '/soundshine?tmp_file_name=' + tmp_csv_file.name.replace('/soundstat/tmp_data/','')
            return redirect(shiny_url)

soundresults/views/view_tests.py
from django.views.generic import ListView
from soundtests.models import SoundTest

class ViewTests(ListView):
    """Lists all available tests

    When a user clicks the "View Test Contents" link on the homepage, this view
    is called.
    """
    context_object_name = 'soundtests'
    model = SoundTest
    paginate_by = 10
    template_name = 'soundresults/view_tests.html'

soundresults/templates/soundresults/view_results.html
{% load static %}
<h2>{{ config }}</h2>
<br>
<br>

<table border=1>
    <tr>
        <td><strong>Master Sound</strong></td>
        <td><strong>User Sound</strong></td>
        <td><strong>Score</strong></td>
        <td><strong>Compare Time</strong></td>
    </tr>
        {% for datum in data %}
            <tr>
                <td pk='{{ datum.sounds.master_sound.pk }}' onclick='play_sound(this)'>{{ datum.sounds.master_sound.phrase2 }}</td>
                <td pk='{{ datum.sounds.user_sound.pk }}' onclick='play_sound(this)'>{{ datum.sounds.user_sound.phrase2 }}</td>
                <td><a href={% url 'soundresults:view_segments' test_slug=test_slug config_pk=config.pk datum_pk=datum.pk %}>{{ datum.score }}</a></td>
                <td>{{ datum.compare_time }}</td>
            </tr>
        {% endfor %}
    </table>
    <br>
    <br>

{# Pagination Section #}
{% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
            <a href='?page={{ page_obj.previous_page_number }}'>previous</a>
            {% endif %}
            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
            <a href='?page={{ page_obj.next_page_number }}'>next</a>
            {% endif %}
        </span>
    </div>
{% endif %}
<br>
<br>
<a href="{% url 'soundtests:index' %}">Back to Home</a>
<!-- Scripts -->
<script type="text/javascript" src="{% static 'javascript/play_sound.js' %}"></script>
<script type="text/javascript" src="{% static 'javascript/jquery-3.3.1.min.js' %}"></script>

soundresults/templates/soundresults/view_runs.html
<h2>{{ name }}</h2>
<br>
<br>

<form action={% url 'soundresults:generate_csv' %} method='POST'>
    {% csrf_token %}
    <table border=1>
        <tr>
            <td></td>
            <td><strong>JSession ID</strong></td>
            <td><strong>Date/Time</strong></td>
            <td><strong>Server Ver.</strong></td>
            <td><strong>Random SNR?</strong></td>
            <td><strong>Added Silence?</strong></td>
        </tr>
            {% for config in runs %}
                <tr>
                    <td><input type='checkbox' name="runs[]" value="{{ config.pk }}"></input></td>
                    <td><a href={% url 'soundresults:view_results' test_slug=config.associated_test.slug config_pk=config.pk %}>{{ config.jsession_id }}</a></td>
                    <td>{{ config.date }}</td>
                    <td>{{ config.server_version }}</td>
                    <td>{{ config.random_snr }}</td>
                    <td>{{ config.added_silence }}</td>
                </tr>
            {% endfor %}
    </table>
    <br>
    <br>
    <button type="Submit" name="download_csv" value="Scientists currently don't know why cats only have four legs instead of eight">Download CSV</button>
    <br>
    <br>
    <button type="Submit" name="explore_data" value="mow">Explore Data (with graphs. there are graphs here)</button>
</form>
<a href="{% url 'soundtests:index' %}">Back to Home</a>

soundresults/templates/soundresults/view_segments.html
<h2>
    Segments of {{datum}} from<br>
    {{config}}
</h2>
<br>
<br>

<table border=1 id='segment_table'>
    <tr>
        <td><strong>Type of Speech</strong></td>
        <td><strong>Text</strong></td>
        <td><strong>Transcription</strong></td>
        <td><strong>Score</strong></td>
        <td><strong>Status</strong></td>
        <td><strong>Master Start</strong></td>
        <td><strong>Master End</strong></td>
        <td><strong>User Start</strong></td>
        <td><strong>User End</strong></td>
    </tr>
        {% for word in segments %}
            <tr depth='0'>
                <td>{{ word.type_of_speech }}</td>
                <td>{{ word.text }}</td>
                <td>{{ word.transcription }}</td>
                <td>{{ word.score }}</td>
                <td>{{ word.raw_status }}</td>
                <td>{{ word.master_start }}</td>
                <td>{{ word.master_end }}</td>
                <td>{{ word.user_start }}</td>
                <td>{{ word.user_end }}</td>
            </tr>
            {% for syllable in word.segments.all %}
                <tr depth='1'>
                    <td style='padding-left:30px;'>{{ syllable.type_of_speech }}</td>
                    <td>{{ syllable.text }}</td>
                    <td>{{ syllable.transcription }}</td>
                    <td>{{ syllable.score }}</td>
                    <td>{{ syllable.raw_status }}</td>
                    <td>{{ syllable.master_start }}</td>
                    <td>{{ syllable.master_end }}</td>
                    <td>{{ syllable.user_start }}</td>
                    <td>{{ syllable.user_end }}</td>
                </tr>

                {% for phoneme in syllable.segments.all %}
                    <tr depth='3'>
                        <td style='padding-left:60px;padding-right:10px'>{{ phoneme.type_of_speech }}</td>
                        <td>{{ phoneme.text }}</td>
                        <td>{{ phoneme.transcription }}</td>
                        <td>{{ phoneme.score }}</td>
                        <td>{{ phoneme.raw_status }}</td>
                        <td>{{ phoneme.master_start }}</td>
                        <td>{{ phoneme.master_end }}</td>
                        <td>{{ phoneme.user_start }}</td>
                        <td>{{ phoneme.user_end }}</td>
                    </tr>
                {% endfor %}
            {% endfor %}
        {% endfor %}
    </table>
    <br>
    <br>
<a href="{% url 'soundtests:index' %}">Back to Home</a>

soundresults/templates/soundresults/view_tests.html
<html>
    {# Table to show tests #}
    <table border=1>
        <tr>
            <td><strong>Test Name</strong></td>
            <td><strong>Description</strong></td>
            <td><strong>Last Run Date</strong></td>
        </tr>
        {% for test in soundtests %}
        <tr>
            <td><a href={% url 'soundresults:view_runs' test_slug=test.slug %}>{{ test.name }}</a></td>
            <td>{{ test.description }}</td>
            <td>{{ test.last_run }}</td>
        </tr>
        {% endfor %}
    </table>

    {# Pagination Section #}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                <a href='?page={{ page_obj.previous_page_number }}'>previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                <a href='?page={{ page_obj.next_page_number }}'>next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
    <br>
    <br>
    <a href={% url 'soundtests:index' %}>Back to Home</a>
</html>